language: java

install:
    - git clone https://github.com/openworm/org.geppetto.model.git -b $TRAVIS_BRANCH
    - cd org.geppetto.model
    - mvn install
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.core.git -b $TRAVIS_BRANCH
    - cd org.geppetto.core
    - mvn install
    - cd ..    


before_install:
    - #!/bin/bash
    - echo "cloning"
    - git clone https://github.com/github/git-lfs.git
    - cd git-lfs
    - echo "checkout commit master"
    - git checkout master
    - echo "pull"
    - git-lfs pull
 
 


