language: java

sudo: required
install:
    - git clone https://github.com/openworm/org.geppetto.model.git
    - cd org.geppetto.model
    - if [[ `git branch -a | egrep "remotes/origin/${TRAVIS_BRANCH}"` ]]; then git checkout $TRAVIS_BRANCH ; else echo "Branch $TRAVIS_BRANCH does not exist for the model bundle, checking out development ..." && git checkout development; fi
    - git status
    - mvn install
    - cd ..

    - git clone https://github.com/openworm/org.geppetto.core.git
    - cd org.geppetto.core
    - if [[ `git branch -a | egrep "remotes/origin/${TRAVIS_BRANCH}"` ]]; then git checkout $TRAVIS_BRANCH ; else echo "Branch $TRAVIS_BRANCH does not exist for the core bundle, checking out development ..." && git checkout development; fi
    - git status
    - mvn install
    - cd .. 
before_install:
    - #!/bin/bash
    - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    - sudo apt-get install git-lfs
    - git lfs install
    - git lfs pull
