language: java

install:
    - git clone https://github.com/openworm/org.geppetto.model.git -b $TRAVIS_BRANCH
    - cd org.geppetto.model
    - mvn install
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.core.git -b $TRAVIS_BRANCH
    - cd org.geppetto.core
    - mvn install
    - cd ..    


before_install:
    - wget https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-darwin-amd64-1.2.0.tar.gz
    - tar -zxvf git-lfs-darwin-amd64-1.2.0.tar.gz
    - export PATH=`pwd`/git-lfs-1.2.0:$PATH
    - echo "https://${GH_TOKEN}@github.com" > .git/credentials
    - git config credential.helper "store --file=.git/credentials"
    - git remote set-url origin https://github.com/PlutoVR/lfs-test.git
    - git lfs install
    - git lfs pull
    
    
    
 
 


