language: java

install:
    - git clone https://github.com/openworm/org.geppetto.model.git -b $TRAVIS_BRANCH
    - cd org.geppetto.model
    - mvn install
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.core.git -b $TRAVIS_BRANCH
    - cd org.geppetto.core
    - mvn install
    - cd ..    


before_install:
    - #!/bin/bash
    - echo "cloning"
    - git clone git@github.com:github/git-lfs.git
    - cd git-lfs
    - echo "checkout commit 4457d7c7c5906025f753579f67f975792235b717"
    - git checkout 4457d7c7c5906025f753579f67f975792235b717
    - echo "scripts/bootstrap"
    - script/bootstrap
    - ls bin
    - cd ..
    - echo "init"
    - git-lfs/bin/git-lfs init
    - echo "fetch"
    - git-lfs/bin/git-lfs fetch
 
 


